version: "3.9"

services:
  db:
    image: postgres:14.7-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: dz1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "dz1" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "15432:5432"
    restart: always
