name: build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: cd docker && docker-compose build
      - name: up postgresql container runs
        run: docker-compose up -d
      - uses: actions/checkout@v4
      - name: set up jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Execute build
        run: make build

      - name: Execute test
        run: make test